### ISSUE TITLE
Mga gigibuhon

### ISSUE THREAD

**Issue by pitzzahh** [pitzzahh/heda#30]
## Tasks
- [ ] Root node should also have a load
- [x] Circuit number validation.
- [ ] Panel sorting based on circuit number.
- [x] Ability to delete a heirarchy
- [ ] Deploy
